{"uuid":"276b1b0e-137b-4b3a-9ca4-ecce2c7b78f4","name":"com.dan.android.LoginTest","children":["2d64c6de-d7e9-4d78-a08d-5f2f3bcb8dc0","2d214480-c8ad-4317-80f1-f93e51bcc1a6"],"befores":[{"name":"preCondition","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Appium HTTP server has started and is listening although we were unable to get an OK response from http://127.0.0.1:4723/status. Make sure both the client and the server use the same base path '/' and check the server log for possible error messages occurrences.\nResponse status code: 404\nResponse payload: {\"status\":9,\"value\":{\"error\":\"unknown command\",\"message\":\"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\",\"stacktrace\":\"\"}}\nNode.js executable path: /usr/local/bin/node\nArguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0]","trace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: Appium HTTP server has started and is listening although we were unable to get an OK response from http://127.0.0.1:4723/status. Make sure both the client and the server use the same base path '/' and check the server log for possible error messages occurrences.\nResponse status code: 404\nResponse payload: {\"status\":9,\"value\":{\"error\":\"unknown command\",\"message\":\"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\",\"stacktrace\":\"\"}}\nNode.js executable path: /usr/local/bin/node\nArguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0]\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:192)\n\tat com.dan.base.BaseTest.preCondition(BaseTest.java:31)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:569)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: io.appium.java_client.service.local.AppiumServerAvailabilityChecker$ConnectionError: ConnectionError\n\tat io.appium.java_client.service.local.AppiumServerAvailabilityChecker.checkResponse(AppiumServerAvailabilityChecker.java:91)\n\tat io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:62)\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:144)\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:185)\n\t... 14 more\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1745416409459,"stop":1745416409514}],"afters":[{"name":"tearDown","status":"passed","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1745416411888,"stop":1745416411889}],"start":1745416409380,"stop":1745416411920}