{"uuid":"4cb982dc-47b7-4855-aeb3-6637b4698e58","historyId":"e9ea1a56d2f37081f713e60875a408df","fullName":"com.dan.ios.LoginTest.placeOrder","labels":[{"name":"package","value":"com.dan.ios.LoginTest"},{"name":"testClass","value":"com.dan.ios.LoginTest"},{"name":"testMethod","value":"placeOrder"},{"name":"parentSuite","value":"Parallel Test Suite"},{"name":"suite","value":"IOS"},{"name":"subSuite","value":"com.dan.ios.LoginTest"},{"name":"host","value":"192.168.1.248.non-exists.ptr.local"},{"name":"thread","value":"25487@192.168.1.248.non-exists.ptr.local.TestNG-tests-2(15)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"placeOrder","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: '192.168.1.248.non-exists.ptr.local', ip: '2402:800:6d62:2108:0:0:0:6%en0'\nBuild info: version: '4.31.0', revision: '1ef9f18787*'\nSystem info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.7.6', java.version: '17.0.13'\nDriver info: io.appium.java_client.ios.IOSDriver\nCommand: [null, newSession {capabilities=[Capabilities {appium:app: /Users/mac/Documents/Appium..., appium:automationName: XCUITest, appium:deviceName: iPhone 13, appium:platformVersion: 15.0, appium:showXcodeLog: true, appium:udid: 91CC769D-8C83-4310-A6EB-9F3..., platformName: IOS}]}]\nCapabilities {appium:app: /Users/mac/Documents/Appium..., appium:automationName: XCUITest, appium:deviceName: iPhone 13, appium:platformVersion: 15.0, appium:showXcodeLog: true, appium:udid: 91CC769D-8C83-4310-A6EB-9F3..., platformName: IOS}","trace":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: '192.168.1.248.non-exists.ptr.local', ip: '2402:800:6d62:2108:0:0:0:6%en0'\nBuild info: version: '4.31.0', revision: '1ef9f18787*'\nSystem info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.7.6', java.version: '17.0.13'\nDriver info: io.appium.java_client.ios.IOSDriver\nCommand: [null, newSession {capabilities=[Capabilities {appium:app: /Users/mac/Documents/Appium..., appium:automationName: XCUITest, appium:deviceName: iPhone 13, appium:platformVersion: 15.0, appium:showXcodeLog: true, appium:udid: 91CC769D-8C83-4310-A6EB-9F3..., platformName: IOS}]}]\nCapabilities {appium:app: /Users/mac/Documents/Appium..., appium:automationName: XCUITest, appium:deviceName: iPhone 13, appium:platformVersion: 15.0, appium:showXcodeLog: true, appium:udid: 91CC769D-8C83-4310-A6EB-9F3..., platformName: IOS}\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)\n\tat io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:270)\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:91)\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:103)\n\tat io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:101)\n\tat com.dan.base.BaseMobileIOS.setUpIOS(BaseMobileIOS.java:42)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:569)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)\n\tat org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:577)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\n\tat org.testng.TestRunner.run(TestRunner.java:621)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: java.io.UncheckedIOException: java.net.ConnectException\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:497)\n\tat io.appium.java_client.internal.filters.AppiumIdempotencyFilter.lambda$apply$0(AppiumIdempotencyFilter.java:35)\n\tat io.appium.java_client.internal.filters.AppiumUserAgentFilter.lambda$apply$0(AppiumUserAgentFilter.java:87)\n\tat org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.lambda$executeAsync$1(JdkHttpClient.java:384)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\t... 4 more\nCaused by: java.net.ConnectException\n\tat java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:574)\n\tat java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)\n\tat org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:456)\n\t... 9 more\nCaused by: java.net.ConnectException\n\tat java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1083)\n\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:198)\n\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:230)\n\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:206)\n\tat java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)\n\tat java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)\n\t... 3 more\nCaused by: java.nio.channels.ClosedChannelException\n\tat java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:195)\n\tat java.base/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:760)\n\tat java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:848)\n\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:183)\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:569)\n\tat java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:185)\n\t... 9 more\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1745085586250,"stop":1745085586252}